### PR TITLE
Add badges generated from workflows to README.md

### PR DESCRIPTION
**Pull request by sebproell**
Part of #42 

For now, I added the badges that Github already generates. I linked to the respective workflow overview. For docs, I link to the readthedocs page.

### CODE REVIEW

**Comment by davidrudlstorfer** [comment]
You could wrap the header and the badges to center them

```
<h1 align="center">
  4C
</h1>

<div align="center">

# put badges here

</div>

```

And we could also use these https://github.com/Ileriayo/markdown-badges badges. There's a specific one for doxygen as well as for readthedocs - there we could link the respective documentations

**Review by amgebauer — APPROVED** [review]

**Comment by amgebauer** [comment]
> You could wrap the header and the badges to center them
> 
> ```
> <h1 align="center">
>   4C
> </h1>
> 
> <div align="center">
> 
> # put badges here
> 
> </div>
> ```
> 
> And we could also use these https://github.com/Ileriayo/markdown-badges badges. There's a specific one for doxygen as well as for readthedocs - there we could link the respective documentations
> 
> [Doxygen](https://4c-multiphysics.github.io/4C/doxygen)

If we want to use these, then we should generate them in our workflow. But I think the ones from Github suffice for now.

**Review by davidrudlstorfer — APPROVED** [review]

**Comment by sebproell** [comment]
Please check the newest version with design input by @davidrudlstorfer!

**Comment by davidrudlstorfer** [comment]
@sebproell we forgot to update the link for the documentation pipeline

**Comment by amgebauer** [comment]
> Please check the newest version with design input by @davidrudlstorfer!

I don't like the new solution. Now, everytime we go to our github repository, we send a request to badgen.net (who can use this to tack us and our users). I think doing so without asking the user is legally problematic.

**Comment by sebproell** [comment]
> I don't like the new solution. Now, everytime we go to our github repository, we send a request to badgen.net (who can use this to tack us and our users). I think doing so without asking the user is legally problematic.

@amgebauer Good point! I did not think about that. Let's not do that.

**Comment by davidrudlstorfer** [comment]
For the sake of simplicity we could just store the plain static badges (for doxygen, rtd and the website) within the repo. This would remove the necessity to generate the badges (which will be static anyways) within the repo @amgebauer @sebproell

**Comment by sebproell** [comment]
I reverted back to the basic version and only added the labels that Github provides. @davidrudlstorfer feel free to take over #42!

**Review by davidrudlstorfer — APPROVED** [review]

**Pull request merged**
