### PR TITLE
Migrate porofluidmulti to vtk based output

### PR DESCRIPTION
**Pull request by c-p-schmidt**
## Description and Context
The taskforce output works to unify the output mechanism. Within this pull request, the migration from the old output mechanism that needs post-processing to the new vtk-based output mechanism is performed for the `porofluidmulti` framework.

The first commit adds the vtk-based output mechanism, while in the second commit, the old output mechanism is deleted.

The comparison of the results of the old and new mechanisms for one test case looked promising. @lkoeglmeier is looking into this in more depth in the following days as she is familiar with the framework to check whether everything works as expected.

### CODE REVIEW

**Comment by lkoeglmeier** [comment]
Thank you very much for your efforts @c-p-schmidt. I looked at five different test files and everything worked fine. The implementation also looks good to me. I'm happy that we can now use the new vtk-based output here.

**Review by lkoeglmeier — APPROVED** [review]

**Review by davidrudlstorfer — APPROVED** [review]
As far as I understand the vtk output is now fully possible for porofluidmulti. Maybe directly add a vtk test?

Otherwise it's looking good

**Comment by mayrmt** [comment]
Since verification by @lkoeglmeier is still pending according to the PR description, should we make this a draft and wait for her final approval?

**Comment by c-p-schmidt** [comment]
> As far as I understand the vtk output is now fully possible for porofluidmulti. Maybe directly add a vtk test?
> 
> Otherwise it's looking good

@davidrudlstorfer: Good suggestion, I really should add a vtk test.
@lkoeglmeier: Do you have a suggestion on which `porofluidmulti` test case I should use for that?

**Comment by c-p-schmidt** [comment]
> Since verification by @lkoeglmeier is still pending according to the PR description, should we make this a draft and wait for the outcome of the planned investigations?

I don't get what you mean. She already posted that she tested several test cases and received the intended result and approved after that comment.

**Comment by lkoeglmeier** [comment]
> > As far as I understand the vtk output is now fully possible for porofluidmulti. Maybe directly add a vtk test?
> > Otherwise it's looking good
> 
> @davidrudlstorfer: Good suggestion, I really should add a vtk test. @lkoeglmeier: Do you have a suggestion on which `porofluidmulti` test case I should use for that?

I would suggest the test case  `poromultielastscatra_2D_quad4_tumor.dat`, since it is a quite complex example that includes fluid exchange and porosity changes, so we could test all output variables.

**Review by davidrudlstorfer — APPROVED** [review]

**Review by lkoeglmeier — APPROVED** [review]

**Comment by c-p-schmidt** [comment]
@bwirthl, this is also of interest to you.

**Pull request merged**
