### PR TITLE
Remove all sfuchs name abbreviations from comments

### PR DESCRIPTION
**Pull request by slfuchs**
## Description and Context

Remove all occurrances of 'sfuchs' from function header comments in the code. This is a leftover from old Baci-times where it was common practice to add the developers name. Nowadays git blame should do the job.

### CODE REVIEW

**Review by amgebauer — APPROVED** [review]
LGTM. Thanks for your contribution @slfuchs!

**Review by davidrudlstorfer — APPROVED** [review]

**Review by ppraegla — APPROVED** [review]
Thanks, @slfuchs :)

**Comment by mayrmt** [comment]
@slfuchs Did you do changes manually or with some script? Just wondering... 

There are plans to purge all names (and dates) from the code base.

**Comment by slfuchs** [comment]
I did it kind of manually searching only for my name abbreviation:
`find . -type f -exec sed -i 's/sfuchs ..\/20../              /g' {} +` 
Seems like I forgot those a few years ago ...

**Comment by sebproell** [comment]
Maybe we should take it one step further and simply remove one-liner boxes before functions in cpp files? They typically serve no purpose as they duplicate the info that is already in the function name. The well-written, longer documentation goes in the header. In the cpp we just want comments on the implementation, when the code is not obvious. 

> There are plans to purge all names (and dates) from the code base.

@mayrmt You want to open an issue for that?

**Comment by mayrmt** [comment]
@sebproell There's a GitLab issue for that. It hasn't been ported to GitHub yet.

**Comment by mayrmt** [comment]
@sebproell See #91.

**Pull request merged**
