### PR TITLE
Set clang as the default compiler at LNM workstations

### PR DESCRIPTION
**Pull request by amgebauer**
Makes LNM ready for #65, has slightly better compile times and more expressive error messages.

### CODE REVIEW

**Review by sebproell — DISMISSED** [review]
@amgebauer AFAIK, you used this specific clang build for a few weeks already?

**Comment by amgebauer** [comment]
Yes, it's my default for a few weeks and I have not yet encountered problems besides the solved so3plast warnings #85.

**Review by c-p-schmidt — APPROVED** [review]

**Comment by sebproell** [comment]
@amgebauer It seems we would need to update libstdc++ on our system if we want to use clang with C++20. This makes me wonder if Clang is the right way to get C++20 access. We can for sure use it once we update our system and have the newer standard library available. Updating the library manually seems cumbersome (although I didn't try it).

**Comment by amgebauer** [comment]
We can still think about it setting clang as standard already today as it provides better error messages and slightly better compile times compared to the current standard gcc9.4

**Pull request closed without merging**
